
CREATE TABLE USER (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (USER_ID),
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    IS_ACTIVATED BOOLEAN,
    REGISTERED_ON DATETIME		
);

CREATE TABLE USER_DETAILS (
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    GENDER VARCHAR(5),
    DOB DATE,
    STATE VARCHAR(30),
    CITY VARCHAR(30),	 
    USER_ID INT,
    INDEX USR_ID (USER_ID),
    FOREIGN KEY (USER_ID) 
        REFERENCES USER(USER_ID)
        ON DELETE CASCADE
);
